### ISSUE TITLE
How to fix this error please ?

### ISSUE THREAD

**Issue by VRVirtuosos** [kijai/ComfyUI-Diffusers-X-Adapter#9]
![Z1valN3N1o](https://github.com/kijai/ComfyUI-Diffusers-X-Adapter/assets/52532437/4c8324fa-11ae-422f-a3c3-0c2acb641092)

**Comment by ashllay** [comment]
From comfyui manager install pip package diffusers>=0.26.0.
![Screenshot_13](https://github.com/kijai/ComfyUI-Diffusers-X-Adapter/assets/5206101/b3bad6ed-4a85-4966-b84c-8938a02e1887)

**Comment by VRVirtuosos** [comment]
That worked , thank you :)
